### ISSUE TITLE
getSource don't load Variables

### ISSUE THREAD

**Issue by Head** [NamPNQ/bower-videogular-flash#1]
I have my video Tag:
source src="{{video.source}}" type="video/flv"

In getSource i debug like this:
if (n.nodeType == 1 && n.tagName.toLowerCase() == 'source') {
     console.log(n);
     src = n.getAttribute('src');
     console.log("src: "+src);
     type = n.getAttribute('type');
     console.log("type: "+type);

and i get:
source src=​"/​xyz.f4v" type=​"video/​flv">​
src:  
type: video/flv 

sometimes the src is set. But most of the time it isn't. Timing problem with Angulars scope? How can i fix this?
Also, it don't load again if i change video.source

**Comment by NamPNQ** [comment]
Temporary you can use videogular in tree: https://github.com/2fdevs/videogular/tree/c30e3c5f9645b8ed4de4ea597b4a6e56a72cf8ac

I will update my code soon

**Comment by Head** [comment]
Sorry, i don't get it. (Angular Beginner) The source in the tree does nothing anymore.
I'm trying since 2 days to reload ($http.get) a f4v video url (also from a different Server... $sce.trustAsResourceUrl??) and display the video dynamic. (div ng-show="video.source")
Your plugin was the only thing i got to display "static" flv's.

I'll wait till you update. Maybe then it will work for me.
Thanks inb4
