### ISSUE TITLE
Update to work with last Videogular version

### ISSUE THREAD

**Issue by Tailzip** [NamPNQ/bower-videogular-flash#5]
Hey,

Is that possible to update the plugin to make it work with the last Videogular version?

Thank you!

EDIT : I was able to make some changes to the code, but now I can't fix that error :

``` javascript
API.mediaElement[0].vjs_setProperty("eventProxyFunction", "onSWFEvent");
Uncaught TypeError: undefined is not a function
```

_API.mediaElement[0]_ is referring to <object> HTML element.

**Comment by NamPNQ** [comment]
I will check and update to new version in tomorrow

**Comment by Tailzip** [comment]
Sounds great! Did you make any progress on this? :)

**Comment by w3t** [comment]
Would also enjoy to get the updated plugin that works with current release of videogular :)

**Comment by NamPNQ** [comment]
Sr, i will try update soon, currently i very busy

**Comment by orollof** [comment]
Really need this to work as well! Thanks in advance NamPNQ

**Comment by MartinWa** [comment]
I need this to be able to support IE8 and Firefox (for MP4)

**Comment by steadystatic** [comment]
Would like to thank you and also voice my support for updating to work with latest Videogular. I'm also getting the error TypeError: d.API.mediaElement is undefined

**Comment by steadystatic** [comment]
I started messing with it...some basics were VG_EVENTS is no longer available. API.videoElement[0] becomes API.videogularElement[0].firstChild (not sure on the first child but it got it working for me).

Here is my patch but I hit a wall with Firefox (which is the whole reason I wanted this fallback) when it couldn't access the SWF properties after SWF creation ("vjs_setProperty"). Here's my patch so far (needs cleanup): 

https://gist.github.com/steadystatic/82b11548494965779347

**Comment by steadystatic** [comment]
Other stuff for controls would also need to be updated like:

videogularElementScope.onUpdateTime

onUpdateTime is not available on that object anymore. Perhaps vgUpdateTime?

**Comment by NamPNQ** [comment]
Check lastest version
